### ISSUE TITLE
UVPlugin-ISO2709ToMarcXML does not properly set VirtualPath for output files

### ISSUE THREAD

**Issue by tomas-knap** [OpenDataNode/ODN-UV-Plugins#1]
The problem is that DPU https://github.com/OpenDataNode/UVPlugin-ISO2709ToMarcXML (develop)
does not properly sets up VirtualPath for output files. Every DPU must define VirtualPath for output file entries using VirtualPathHelper.

Solution: VirtualPath must be properly set up for ISO2709ToMarcXML

Created based on the findings in https://github.com/UnifiedViews/Plugins/issues/128

**Comment by skrchnavy** [comment]
depends on OpenDataNode/UVPlugin-ISO2709ToMarcXML#1

**Comment by skrchnavy** [comment]
closed. managed in DPUs repository
